### ISSUE TITLE
Fix Add/Update Salary page ("Forbidden")

### ISSUE THREAD

**Issue by kenoshabrickk** [openoversightva/openoversight#100]
![image](https://github.com/openoversightva/openoversight/assets/118392825/f8e7db15-1416-4fd0-985d-a6a311c589dc)

If we did this on purpose to ensure data quality I am open to that approach. I use this semi-frequently when I come across data that's missing from the site but which I see in our roster FOIA archives, which feels useful but I can see it both ways.

**Comment by kenoshabrickk** [comment]
However, if this is on purpose to ensure data quality I am open to that approach

**Comment by kenoshabrickk** [comment]
@bryan-va 
![screencast-openoversightva org-2023 08 12-16_49_06](https://github.com/openoversightva/openoversight/assets/118392825/b629cda4-55a2-4969-bf76-9d826a39086f)

**Comment by kfinity** [comment]
Interesting. What user were you logged in as here?

**Comment by kenoshabrickk** [comment]
Looks fixed! Thank you<3
