### ISSUE TITLE
Add landing page for each department

### ISSUE THREAD

**Issue by kenoshabrickk** [openoversightva/openoversight#115]
- @kfinity we've discussed this & I think you proposed it
- Would be a good goal for our target date of 12/31 (also target date for loading 2023 rosters?) - maybe?
- Could have volunteers help with data collection aspect of this too
- We can start a shared spreadsheet for this if you want & can discuss what each page should include

**Comment by kfinity** [comment]
Yeah, collecting the stats could definitely be done by volunteers. We have locality for most of them - I'd like to see Population as a field, and maybe Budget (or spending or whatever). Could also be interesting to track asset forfeiture, or government grants and other stuff? Probably a text field for a description?

I like the idea of collaborating on sketching out ideas for what we want it to look like, then doing the coding.
