### ISSUE TITLE
Priority: Change main footer (see note).

### ISSUE THREAD

**Issue by kenoshabrickk** [openoversightva/openoversight#52]
**Current Footer:**

OpenOversightVA
This is a fork of OpenOversight by Lucy Parsons Labs in Chicago, IL.
**[Lucy Parsons Labs](https://lucyparsonslabs.com/)**
[Download department data](https://openoversightva.org/download/all)

---
**New Footer:**

**OpenOversightVA**
Virginia's only statewide police transparency database. Codebase and concept thanks to the original [OpenOversight](https://openoversightva.com) instance by Lucy Parsons Labs in Chicago, IL. We are volunteer-run and donation-funded.
[Download Our Data](https://openoversightva.org/download/all)

---

_(Or something like that, but formatted better or with the email icon for reach for the Contact Us maybe? Am attached to the copy, not the format.)_

****Note:** Delete current Contact Us links to our Github, unused Twitter, and the Riseup email address. Replace with these links:** 

**Contact Us**
[Admin](alice@openoversightva.org) | [Legal](legal@openoversightva.org) | [Press](press@openoversightva.org)

**Comment by ob-codes** [comment]
hey i can give it a shot. can you please assign it to me.
