### ISSUE TITLE
Incidents page could really use a search function (by department, by officer, by keyword, etc.!)

### ISSUE THREAD

**Issue by kfinity** [openoversightva/openoversight#95]
Currently the incidents/ page only lets a user filter by the Report Number, or by the date of incident. A free text search field would be very helpful with searching for incidents involving specific people or events.

**Comment by kenoshabrickk** [comment]
I've thought this so many times, thank you for adding this! I also saw we have a new search incidents by date feature & I am very extremely into this. Thank you so much to whoever's working on that & it looks great.

A search by agency option would be kinda cool too. In an ideal world, we could search for officers' names to check if they're tagged in any incidents & the ability to filter incidents by type (this one would require us to have categories _and_ tags & there is not a way to categorize incidents right now, I think). Maybe one day.

There is a lot of information on the site and it is not super easy for a user to explore it as of now, which I often feel guilty about, so I think this was a great issue to open for accessibility & I am here for it [❤️][💯] Thank you guys

**Comment by kfinity** [comment]
Added department search and simple exact-match case-insensitive search for incident description.
